### ISSUE TITLE
7.0.0 release on GitHub giving "ImportError: cannot import name 'Configuration'"

### ISSUE THREAD

**Issue by mahtDFR** [Ghostkeeper/SVGToolpathReader#11]
Github [release 7.0.0](https://github.com/Ghostkeeper/SVGToolpathReader/releases/download/v1.2.0/SVGToolpathReader1.2.0-sdk7.0.0.curapackage) doesn't seem to play nice with Cura 4.5 for me. However the version uploaded to the Marketplace (1.2.0) does. Am I going wrong somewhere?

4.5 log output:
```
Exception: Import error loading module SVGToolpathReader
2020-04-02 16:13:01,819 - ERROR - [MainThread] UM.Logger.logException [102]: Traceback (most recent call last):
2020-04-02 16:13:01,822 - ERROR - [MainThread] UM.Logger.logException [102]:   File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\PluginRegistry.py", line 606, in _findPlugin
2020-04-02 16:13:01,824 - ERROR - [MainThread] UM.Logger.logException [102]:   File "imp.py", line 245, in load_module
2020-04-02 16:13:01,826 - ERROR - [MainThread] UM.Logger.logException [102]:   File "imp.py", line 217, in load_package
2020-04-02 16:13:01,828 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 693, in _load
2020-04-02 16:13:01,830 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2020-04-02 16:13:01,832 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2020-04-02 16:13:01,835 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2020-04-02 16:13:01,837 - ERROR - [MainThread] UM.Logger.logException [102]:   File "C:\Users\m.jani\AppData\Roaming\cura\4.5\plugins\SVGToolpathReader\SVGToolpathReader\__init__.py", line 7, in <module>
2020-04-02 16:13:01,839 - ERROR - [MainThread] UM.Logger.logException [102]:     from . import SVGToolpathReader
2020-04-02 16:13:01,841 - ERROR - [MainThread] UM.Logger.logException [102]:   File "C:\Users\m.jani\AppData\Roaming\cura\4.5\plugins\SVGToolpathReader\SVGToolpathReader\SVGToolpathReader.py", line 16, in <module>
2020-04-02 16:13:01,844 - ERROR - [MainThread] UM.Logger.logException [102]:     from . import Configuration
2020-04-02 16:13:01,846 - ERROR - [MainThread] UM.Logger.logException [102]: ImportError: cannot import name 'Configuration'
2020-04-02 16:13:01,850 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [680]: Could not find plugin SVGToolpathReader
2020-04-02 16:13:01,853 - ERROR - [MainThread] UM.Logger.logException [98]: Exception: Import error loading module SVGToolpathReader
2020-04-02 16:13:01,856 - ERROR - [MainThread] UM.Logger.logException [102]: Traceback (most recent call last):
2020-04-02 16:13:01,859 - ERROR - [MainThread] UM.Logger.logException [102]:   File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\PluginRegistry.py", line 606, in _findPlugin
2020-04-02 16:13:01,861 - ERROR - [MainThread] UM.Logger.logException [102]:   File "imp.py", line 245, in load_module
2020-04-02 16:13:01,863 - ERROR - [MainThread] UM.Logger.logException [102]:   File "imp.py", line 217, in load_package
2020-04-02 16:13:01,865 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 693, in _load
2020-04-02 16:13:01,868 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2020-04-02 16:13:01,870 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2020-04-02 16:13:01,872 - ERROR - [MainThread] UM.Logger.logException [102]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2020-04-02 16:13:01,874 - ERROR - [MainThread] UM.Logger.logException [102]:   File "C:\Users\m.jani\AppData\Roaming\cura\4.5\plugins\SVGToolpathReader\SVGToolpathReader\__init__.py", line 7, in <module>
2020-04-02 16:13:01,877 - ERROR - [MainThread] UM.Logger.logException [102]:     from . import SVGToolpathReader
2020-04-02 16:13:01,879 - ERROR - [MainThread] UM.Logger.logException [102]:   File "C:\Users\m.jani\AppData\Roaming\cura\4.5\plugins\SVGToolpathReader\SVGToolpathReader\SVGToolpathReader.py", line 16, in <module>
2020-04-02 16:13:01,881 - ERROR - [MainThread] UM.Logger.logException [102]:     from . import Configuration
2020-04-02 16:13:01,883 - ERROR - [MainThread] UM.Logger.logException [102]: ImportError: cannot import name 'Configuration'
```

**Comment by Ghostkeeper** [comment]
I think I made a mistake with the upload here on Github. I may have used an older version from before I updated the CMakeLists with the new files. Thanks for bringing it to my attention. I'll check it out later tonight.

**Comment by Ghostkeeper** [comment]
Indeed, they were outdated. Thanks for checking! I tested these from source, but this shows how important it is to test using actual builds as well.
